package com.ezcloud.mcp.server.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA Entity representing a product in the inventory.
 *
 * This entity maps to the "products" table in the H2 in-memory database.
 * It stores core product information that can be queried and modified
 * through the MCP tools exposed by ProductService.
 *
 * The @Data annotation from Lombok automatically generates:
 * - Getters and setters for all fields
 * - equals() and hashCode() methods
 * - toString() method
 */
@Entity
@Table(name = "products")
@Data
@NoArgsConstructor
public class Product {

    /**
     * Unique identifier for the product.
     * Auto-generated by the database using identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The display name of the product (e.g., "Laptop", "Wireless Mouse").
     */
    private String name;

    /**
     * The category this product belongs to.
     * Common categories: Electronics, Books, Clothing, Appliances.
     */
    private String category;

    /**
     * The price of the product in USD.
     */
    private Double price;

    /**
     * The current stock quantity available in inventory.
     */
    private Integer stock;

    /**
     * Convenience constructor for creating a new product without an ID.
     * The ID will be auto-generated upon persistence.
     *
     * @param name     The product name
     * @param category The product category
     * @param price    The product price in USD
     * @param stock    The initial stock quantity
     */
    public Product(String name, String category, Double price, Integer stock) {
        this.name = name;
        this.category = category;
        this.price = price;
        this.stock = stock;
    }
}
